TYPE_LIGHT_SENSOR = 0
TYPE_SOIL_SENSOR = 1
TYPE_HUMIAIR_SENSOR = 2
TYPE_TEMP_SENSOR = 3
TYPE_DIGITAL_OUTPUT = 4

MQTT_SERVER = "mqtt.ohstem.vn"
MQTT_PORT = 1883
MQTT_USERNAME = "nguyentruongthan"
MQTT_PASSWORD = ""

HEADER_CREATE = 0
HEADER_DELETE = 1
HEADER_SENSOR_VALUE = 2
HEADER_CONTROL_DEVICE = 3
HEADER_GET_DEVICE = 4
HEADER_CREATE_SCHEDULER = 5