const TYPE_LIGHT_SENSOR = 0
const TYPE_SOIL_SENSOR = 1
const TYPE_HUMIAIR_SENSOR = 2
const TYPE_TEMP_SENSOR = 3
const TYPE_DIGITAL_OUTPUT = 4

const HEADER_CREATE = 0
const HEADER_DELETE = 1
const HEADER_SENSOR_VALUE = 2
const HEADER_CONTROL_DEVICE = 3
const HEADER_GET_DEVICE = 4
const HEADER_CREATE_SCHEDULER = 5
const HEADER_ACK = 6
const HEADER_GET_SCHEDULER = 7
const HEADER_DELETE_SCHEDULER = 8
const HEADER_GET_LATEST_VALUE = 9
const HEADER_LATEST_VALUE = 10
const HEADER_GET_RULE = 11
const HEADER_CREATE_RULE = 12
const HEADER_GET_IS_AUTO = 13
const HEADER_CREATE_IS_AUTO = 14
const HEADER_DELETE_RULE = 15
const CONDITION_LESS = "<"
const CONDITION_EQUAL = "=="
const CONDITION_GREATER = ">"

module.exports = {
  TYPE_LIGHT_SENSOR,
  TYPE_SOIL_SENSOR,
  TYPE_HUMIAIR_SENSOR,
  TYPE_TEMP_SENSOR,
  TYPE_DIGITAL_OUTPUT,
  HEADER_CREATE,
  HEADER_DELETE,
  HEADER_SENSOR_VALUE,
  HEADER_CONTROL_DEVICE,
  HEADER_GET_DEVICE,
  HEADER_CREATE_SCHEDULER,
  HEADER_ACK,
  HEADER_GET_SCHEDULER,
  HEADER_DELETE_SCHEDULER,
  HEADER_GET_LATEST_VALUE,
  HEADER_LATEST_VALUE,
  CONDITION_LESS,
  CONDITION_EQUAL,
  CONDITION_GREATER,
  HEADER_GET_RULE,
  HEADER_CREATE_RULE,
  HEADER_GET_IS_AUTO,
  HEADER_CREATE_IS_AUTO,
  HEADER_DELETE_RULE
};