const TYPE_LIGHT_SENSOR = 0
const TYPE_SOIL_SENSOR = 1
const TYPE_HUMIAIR_SENSOR = 2
const TYPE_TEMP_SENSOR = 3
const TYPE_DIGITAL_OUTPUT = 4

const HEADER_CREATE = 0
const HEADER_DELETE = 1
const HEADER_SENSOR_VALUE = 2
const HEADER_CONTROL_DEVICE = 3
const HEADER_GET_DEVICE = 4
const HEADER_CREATE_SCHEDULER = 5
const HEADER_ACK = 6
const HEADER_GET_SCHEDULER = 7
const HEADER_DELETE_SCHEDULER = 8
const HEADER_GET_LATEST_VALUE = 9
const HEADER_LATEST_VALUE = 10
module.exports = {
  TYPE_LIGHT_SENSOR,
  TYPE_SOIL_SENSOR,
  TYPE_HUMIAIR_SENSOR,
  TYPE_TEMP_SENSOR,
  TYPE_DIGITAL_OUTPUT,
  HEADER_CREATE,
  HEADER_DELETE,
  HEADER_SENSOR_VALUE,
  HEADER_CONTROL_DEVICE,
  HEADER_GET_DEVICE,
  HEADER_CREATE_SCHEDULER,
  HEADER_ACK,
  HEADER_GET_SCHEDULER,
  HEADER_DELETE_SCHEDULER,
  HEADER_GET_LATEST_VALUE,
  HEADER_LATEST_VALUE
};