let TYPE_LIGHT_SENSOR = 0
let TYPE_SOIL_SENSOR = 1
let TYPE_DHT_SENSOR = 2
let TYPE_DIGITAL_OUTPUT = 3

let HEADER_CREATE = 0
let HEADER_DELETE = 1
let HEADER_SENSOR_VALUE = 2
let HEADER_CONTROL_DEVICE = 3
let HEADER_GET_DEVICE = 4
let HEADER_CREATE_SCHEDULER = 5
module.exports = {
  TYPE_LIGHT_SENSOR,
  TYPE_SOIL_SENSOR,
  TYPE_DHT_SENSOR,
  TYPE_DIGITAL_OUTPUT,
  HEADER_CREATE,
  HEADER_DELETE,
  HEADER_SENSOR_VALUE,
  HEADER_CONTROL_DEVICE,
  HEADER_GET_DEVICE,
  HEADER_CREATE_SCHEDULER
};